config/routes.rb
Rails.application.routes.draw do
  get 'tweets/index', to: 'tweets#index'
  root 'tweets#index'
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :message , presence: true
    validates :message , length: { maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  
  def new
    @tweet= Tweet.new
  end
  
  def show
   @tweet = Tweet.find(params[:id])
  end
  
  def create
    @tweet = Tweet.new(message: params[:tweet][:message])
    if @tweet.save
      redirect_to '/'
    else
      render 'new'
    end
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to '/'
  end
  
  def update
    @tweet = Tweet.find(params[:id])
    @tweet = Tweet.update(message: params[:tweet][:message])
    redirect_to '/'
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  

  <body>
    <div id="container">
      <div id="header">
        <%= render 'header' %>
      </div>
      <div id="sidebar" %>
        <%= render 'sidebar' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer">
      <%= render 'footer' %>
    </div>
   </div>
  </body>
  </head>
</html>

app/views/tweets/_footer.html.erb
©️twitter.com

app/views/tweets/_header.html.erb
 <img src="/assets/aaa.png">

app/views/tweets/_sidebar.html.erb
<font size="5">近畿大学</font><br>
@kinkidaigakuPR<br>
近畿大学総務部広報室のTwitter公式アカウントです。近畿大学ホームページの更新情報を中心に、大学に関する情報を発信していきます。個別のお問い合わせには返信を行っていませんので、ご了承ください。<br>
<br>
大阪府大阪市<br>
<a herf="instagram.com/kinkidaigakupr/">instagram.com/kinkidaigakupr/</a><br>
2010年12月に登録<br>
<%= link_to 'ツイート', new_tweet_path %>

app/views/tweets/edit.html.erb
<%= form_for(@tweet , url: {action: :update} ) do |f| %>
  <%= f.label :message, 'メッセージ' %>
  <%= f.text_field :message %>
  <%= f.submit '更新' %>
<% end %>
<%= link_to '戻る', root_path %>

app/views/tweets/index.html.erb
<% t = Time.current %>
<div class="top">
<p>ツイート　ツイートと返信　メディア</p>
<div id="content"></div>
<% @tweets.each do |com| %>
 <p>
     <%= link_to com.message, "/tweets/#{com.id}" %>
     <%= (t-com.created_at).to_i.to_s + "秒前" %>
     <%= link_to '消去', "/tweets/#{com.id}", method: :delete %>
     <%= link_to '編集', "/tweets/#{com.id}/edit" %>
 </p>
<% end %>
</div>
</div>

app/views/tweets/new.html.erb
<div class="style">
<%= form_for @tweet , url: {action: :create}  do |f| %>
  <%= f.label :message, '今どうしてる？' %>
  <%= f.text_field :message %>
  <%= f.submit 'ツイート' %>
<% end %>
<%= link_to 'キャンセル' , root_path %>

</div>

app/views/tweets/show.html.erb
<%= @tweet.message %>